version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_HOST=$DB_HOST
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - ./db:/var/lib/mysql
      - ./script/init.sql:/docker-entrypoint-initdb.d/1.sql

  app:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    ports:
      - "$APP_PORT:$APP_PORT"
    stdin_open: true
    tty: true

volumes:
  db:
